### ISSUE TITLE
App starts with message 'BikeHist wurde beendet'.

### ISSUE THREAD

**Issue by chs8691** [chs8691/BikeHist#1]
But the the App is starting normally.

**Comment by chs8691** [comment]
Could not verify this problem. Tested on Nexus 4 and Intellibook, but seems all fine. There must be an unknown precondition. At the moment, nothing can be done.

**Comment by chs8691** [comment]
Found the exception:
09-29 10:34:50.090     592-5084/? I/ActivityManager﹕ START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.egh.bikehist.pro/de.egh.bikehist.MainActivity (has extras)} from uid 10035 on display 0
09-29 10:34:50.113     592-5084/? V/WindowManager﹕ addAppToken: AppWindowToken{3d3adc40 token=Token{171f4bc3 ActivityRecord{20478b72 u0 de.egh.bikehist.pro/de.egh.bikehist.MainActivity t21457}}} to stack=1 task=21457 at 1
09-29 10:34:50.215     592-5069/? V/WindowManager﹕ Adding window Window{39feecbe u0 de.egh.bikehist.pro/de.egh.bikehist.MainActivity} at 27 of 33 (after Window{fee5e48 u0 de.egh.bikehist.pro/de.egh.bikehist.MainActivity})
09-29 10:34:50.317    9066-9066/? D/AndroidRuntime﹕ Shutting down VM
    --------- beginning of crash
09-29 10:34:50.319    9066-9066/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: de.egh.bikehist.pro, PID: 9066
    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
            at android.support.v4.app.aa.u(Unknown Source)
            at android.support.v4.app.aa.a(Unknown Source)
            at android.support.v4.app.e.a(Unknown Source)
            at android.support.v4.app.e.a(Unknown Source)
            at de.egh.bikehist.MainActivity.o(Unknown Source)
            at de.egh.bikehist.MainActivity.m(Unknown Source)
            at de.egh.bikehist.MainActivity.a(Unknown Source)
            at de.egh.bikehist.MainActivity.a(Unknown Source)
            at de.egh.bikehist.a.onReceive(Unknown Source)
            at android.support.v4.a.w.a(Unknown Source)
            at android.support.v4.a.w.a(Unknown Source)
            at android.support.v4.a.x.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

This happens in the following way:
Install the pro release APK locally. The app will be called. Press the mid buttom aof the device and start the app by clicking the launcher icon.

**Comment by chs8691** [comment]
Solved.
