### ISSUE TITLE
Export failed

### ISSUE THREAD

**Issue by chs8691** [chs8691/BikeHist#4]
Exception, when exporting in free/debug-apk:

10-01 12:00:22.474  24810-25110/de.egh.bikehist.free E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #4
    Process: de.egh.bikehist.free, PID: 24810
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:304)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'de.egh.bikehist.sync.SyncController$EntityStatistic de.egh.bikehist.sync.SyncController$Statistic.bike' on a null object reference
            at de.egh.bikehist.sync.SyncController.runExport(SyncController.java:258)
            at de.egh.bikehist.persistance.SaveDataService$2.run(SaveDataService.java:299)
            at de.egh.bikehist.persistance.SaveDataService$WorkerTask.doInBackground(SaveDataService.java:529)
            at de.egh.bikehist.persistance.SaveDataService$WorkerTask.doInBackground(SaveDataService.java:514)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by chs8691** [comment]
To much code cleaning done... Reactivated statistic now.
